# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('website', models.URLField()),
            ],
            options={
                'verbose_name_plural': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expertise', models.CharField(choices=[('Developer', 'Developer'), ('Designer', 'Designer'), ('Finance Expert', 'Finance Expert')], max_length=100)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_hire', models.CharField(choices=[('Developer', 'Developer'), ('Designer', 'Designer'), ('Finance Expert', 'Finance Expert')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('company', models.CharField(max_length=100)),
            ],
        ),
    ]
