# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-14 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
