# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freelancingapp', '0004_auto_20171215_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='to_hire',
            field=models.CharField(blank=True, choices=[('Developer', 'Developer'), ('Designer', 'Designer'), ('Finance Expert', 'Finance Expert')], max_length=100, null=True),
        ),
    ]
